server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update


check-user-scopes: true
role:
   channel: channel.oauth.role

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjV7EwLV63bpm+lbzTOV+
          8hFwoCQ5GnC7nSsEzJTZYOyyPhsTHuM9c2QQzZJuBgDa9fp8VlOgdTYCTcr4j5HK
          FPeKLTDKDWPoiGWAnkPeRWqvJfDe3lpdPUoZgNDHE95xCwv9YusX5PwKUTj1488U
          lwnLf+/cdK7ZWIG7q9vGyXvj18pcYJhrEEbW73B5ajYaxgep18hB7KQWCRvuxp5P
          ODeEMmFDlf7OhCoQDSwJlButNukLTODdHsR7dkaGWt1k+NjbyjpyHbGJ0BU92h43
          evGzd2/EPK8TC0sgHZIjiiZrn7Sl8zspqMUyEiWKurdbinXYOzEmvnvFPvKqFQ9R
          cwIDAQAB
          -----END PUBLIC KEY-----